### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [CrazyMechanic/project-1#1]
1)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/229334424-cda99495-a6db-480f-ab55-8d79560a8e2b.png)

2)
???
![image](https://user-images.githubusercontent.com/8464662/229334465-4aa63d1d-d1b5-47c6-bc9d-12f53b2eeb64.png)
![image](https://user-images.githubusercontent.com/8464662/229334478-4903463d-71f8-43a2-8c28-18a17aa6f56d.png)

**Comment by CrazyMechanic** [comment]
работа над ошибками - проведена
